name: my_money_tracker
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cloud_firestore: ^5.0.2
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  get: ^4.6.6
  image_picker: ^1.1.2
  velocity_x: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/

  fonts:
    - family: sans_bold
      fonts:
        - asset: assets/fonts/sans_bold.ttf
    - family: sans_regular
      fonts:
        - asset: assets/fonts/sans_regular.ttf
    - family: sans_semibold
      fonts:
        - asset: assets/fonts/sans_semibold.ttf
